"use client";
import { FormEvent,useEffect,useRef,useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { AlertTriangle,BellRing,ChevronRight,CloudRain,Crosshair,History,LoaderCircle,LogOut,MapPinned,Search,ShieldCheck,Sparkles,UserRound } from "lucide-react";
import { riskApi,type RiskResponse } from "@/lib/risk-api";
import { supabase } from "@/lib/supabase-browser";
import RiskMap from "./risk-map";
const initial:RiskResponse={region:{name:"서울특별시 관악구",latitude:37.4784,longitude:126.9516},rainfall:{forecastMm:63,accumulated3dMm:124},risks:{overall:{score:78,level:"위험"},landslide:{score:83,level:"위험"},flood:{score:65,level:"주의"},cascade:{score:78,level:"위험"}},analysis:{headline:"집중호우로 인한 연쇄재난 가능성에 주의하세요.",description:"최근 누적 강수량이 높고 산사태 위험지역과 과거 침수지역이 인접해 있습니다. 산사태 발생 시 토사가 배수시설을 막아 저지대 침수로 이어질 가능성이 있습니다.",flow:["집중호우","토양 포화","산사태","침수 확산"]},map:{features:{type:"FeatureCollection",features:[]}},meta:{source:"demo",analyzedAt:new Date().toISOString()}};
const riskClass=(v:string)=>v==="위험"||v==="매우 위험"?"risk-danger":v==="경계"?"risk-alert":v==="주의"?"risk-caution":v==="관심"?"risk-interest":"risk-safe";
function pointInRing(lng:number,lat:number,ring:number[][]){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const[xi,yi]=ring[i];const[xj,yj]=ring[j];if((yi>lat)!==(yj>lat)&&lng<(xj-xi)*(lat-yi)/(yj-yi)+xi)inside=!inside}return inside}
function isInsideRiskArea(lng:number,lat:number,features:GeoJSON.FeatureCollection){return features.features.some(feature=>{const geometry=feature.geometry;if(!geometry)return false;if(geometry.type==="Polygon")return pointInRing(lng,lat,geometry.coordinates[0] as number[][]);if(geometry.type==="MultiPolygon")return geometry.coordinates.some(polygon=>pointInRing(lng,lat,polygon[0] as number[][]));return false})}
type AuthUser={id:string;displayName:string;email:string};
export default function Dashboard(){
 const[query,setQuery]=useState("");const[data,setData]=useState(initial);const[notice,setNotice]=useState("검색하거나 지도를 클릭해 위험도를 확인하세요.");const[loading,setLoading]=useState(false);const[view,setView]=useState<"map"|"profile">("map");const[layer,setLayer]=useState("종합");const[splash,setSplash]=useState(true);const[history,setHistory]=useState<string[]>([]);const[user,setUser]=useState<AuthUser|null>(null);const[authLoading,setAuthLoading]=useState(true);const[boundaryAlert,setBoundaryAlert]=useState(false);const watchRef=useRef<number|null>(null);const insideRef=useRef(false);const dataRef=useRef(data);dataRef.current=data;
 const historyKey=(id?:string)=>`safelink-history:${id??"guest"}`;
 useEffect(()=>{const timer=setTimeout(()=>setSplash(false),950);const applySession=(session:Awaited<ReturnType<typeof supabase.auth.getSession>>["data"]["session"])=>{const account=session?.user;const nextUser=account?{id:account.id,displayName:String(account.user_metadata?.full_name||account.user_metadata?.name||account.email||"Google 사용자"),email:account.email||""}:null;setUser(nextUser);setAuthLoading(false);try{const saved=localStorage.getItem(historyKey(nextUser?.id));setHistory(saved?JSON.parse(saved):[])}catch{setHistory([])}};supabase.auth.getSession().then(({data})=>applySession(data.session));const{data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>applySession(session));return()=>{clearTimeout(timer);subscription.unsubscribe()}},[]);
 function remember(name:string){setHistory(previous=>{const next=[name,...previous.filter(x=>x!==name)].slice(0,8);localStorage.setItem(historyKey(user?.id),JSON.stringify(next));return next})}
 async function signIn(){setAuthLoading(true);const{error}=await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:window.location.origin,queryParams:{prompt:"select_account"}}});if(error){setAuthLoading(false);setNotice(`Google 로그인 오류: ${error.message}`)}}
 async function signOut(){await supabase.auth.signOut();setView("map");setNotice("로그아웃되었습니다.")}
 async function run(request:()=>Promise<RiskResponse>){setLoading(true);setNotice("위험 정보를 분석하는 중입니다…");try{const result=await request();setData(result);remember(result.region.name);setView("map");setNotice(`${result.region.name} 분석이 완료되었습니다.${result.meta.source==="demo"?" 현재 시연용 데이터입니다.":""}`)}catch(e){setNotice(e instanceof Error?e.message:"분석 중 오류가 발생했습니다.")}finally{setLoading(false)}}
 function search(e:FormEvent){e.preventDefault();if(!query.trim()){setNotice("검색할 지역명을 입력해 주세요.");return}run(()=>riskApi.search(query.trim()))}
 function locate(){if(!navigator.geolocation){setNotice("현재 위치를 사용할 수 없습니다.");return}setNotice("현재 위치를 확인하는 중입니다…");navigator.geolocation.getCurrentPosition(p=>run(()=>riskApi.location(p.coords.latitude,p.coords.longitude)),()=>setNotice("위치 권한을 허용하면 현재 위치를 분석할 수 있어요."))}
 async function toggleBoundaryAlert(){if(boundaryAlert){if(watchRef.current!==null)navigator.geolocation.clearWatch(watchRef.current);watchRef.current=null;insideRef.current=false;setBoundaryAlert(false);setNotice("위험 경계 알림을 껐습니다.");return}if(!navigator.geolocation){setNotice("이 기기에서는 위치 알림을 사용할 수 없습니다.");return}if("Notification" in window&&Notification.permission==="default")await Notification.requestPermission();watchRef.current=navigator.geolocation.watchPosition(position=>{const inside=isInsideRiskArea(position.coords.longitude,position.coords.latitude,dataRef.current.map.features);if(inside&&!insideRef.current){const message=`${dataRef.current.region.name} 위험 경계에 진입했습니다. 우회 경로를 확인하세요.`;setNotice(message);if("Notification" in window&&Notification.permission==="granted")new Notification("SafeLink 위험 경계 알림",{body:message})}insideRef.current=inside},()=>{setBoundaryAlert(false);setNotice("위치 권한을 허용해야 위험 경계 알림을 받을 수 있어요.")},{enableHighAccuracy:true,maximumAge:15000,timeout:20000});setBoundaryAlert(true);setNotice("위험 경계 알림이 켜졌습니다. 이 페이지를 열어둔 동안 현재 위치를 확인합니다.")}
 useEffect(()=>()=>{if(watchRef.current!==null)navigator.geolocation.clearWatch(watchRef.current)},[]);
 return <main>{splash&&<div className="splash"><div className="splash-mark"><ShieldCheck/></div><p>SEOUL <b>SAFELINK</b></p><span>도시 재난 위험 통합 분석</span></div>}<header className="topbar"><button className="brand brand-button" onClick={()=>setView("map")}><span className="brand-mark"><ShieldCheck size={21}/></span><span>SEOUL <b>SAFELINK</b></span></button><nav><button className={view==="map"?"active":""} onClick={()=>setView("map")}>위험지도</button><button className={view==="profile"?"active":""} onClick={()=>setView("profile")}>프로필</button></nav>{user?<div className="account"><button onClick={()=>setView("profile")}><span className="account-avatar"><UserRound size={16}/></span><span className="account-copy"><b>{user.displayName}</b><small>{user.email}</small></span></button><button className="account-signout" onClick={signOut} aria-label="로그아웃"><LogOut size={15}/><span>로그아웃</span></button></div>:<button className="login google-login" onClick={signIn} disabled={authLoading}><span className="google-mark" aria-hidden="true">G</span><span>{authLoading?"로그인 확인 중…":"Google 계정으로 로그인"}</span></button>}</header>
 {view==="profile"?<Profile user={user} history={history} onSignIn={signIn} authLoading={authLoading} clear={()=>{setHistory([]);localStorage.removeItem(historyKey(user?.id))}} openMap={()=>setView("map")} select={item=>{setQuery(item.replace("서울특별시 ",""));run(()=>riskApi.search(item))}}/>:<><section className="search-band"><div><p className="eyebrow">서울 재난 위험 통합 분석</p><h1>지금, 어디가 위험한가요?</h1></div><form onSubmit={search} className="search-box"><Search size={20}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="지역명 또는 목적지를 입력하세요"/><Button type="button" variant="ghost" onClick={locate}><Crosshair size={19}/><span>현재 위치</span></Button><Button type="submit" disabled={loading}>{loading?<LoaderCircle className="spin"/>:"분석하기"}</Button></form><p className="notice">{notice}</p></section>
 <section id="dashboard" className="dashboard-wrap"><div className="summary-row"><div><span className="live-dot"/> 위험 분석 <strong>{data.region.name}</strong></div><div className="rain-summary"><CloudRain size={19}/><span>예상 강수 <b>{data.rainfall.forecastMm}mm</b></span><i/><span>3일 누적 <b>{data.rainfall.accumulated3dMm}mm</b></span></div></div><div className="main-grid"><section className="map-card"><div className="map-toolbar"><span>위험지역 통합지도</span><div>{["종합","산사태","침수"].map(item=><button key={item} className={layer===item?"selected":""} onClick={()=>{setLayer(item);setNotice(`${item} 위험도 레이어를 표시하고 있습니다.`)}}>{item}</button>)}</div></div><RiskMap data={data} onLocation={(lat,lng)=>run(()=>riskApi.location(lat,lng))}/></section><aside className="risk-panel"><div className="overall-card"><div><p>종합 위험도</p><span>강우·지형·과거 이력 종합</span></div><div className="score-ring"><b>{data.risks.overall.score}</b><small>/100</small></div><strong className={riskClass(data.risks.overall.level)}>{data.risks.overall.level}</strong></div><div className="risk-list"><Risk icon={<AlertTriangle/>} tone="red" title="산사태 위험" sub="위험지도 + 누적강수" value={data.risks.landslide.level}/><Risk icon={<CloudRain/>} tone="blue" title="침수 위험" sub="침수이력 + 예상강수" value={data.risks.flood.level}/><Risk icon={<Sparkles/>} tone="amber" title="연쇄재난 위험" sub="산사태 → 배수장애 → 침수" value={data.risks.cascade.level}/></div><p className="demo-note">{data.meta.source==="demo"?"현재는 시연 응답입니다. FastAPI 주소 설정 후 실제 응답으로 자동 전환됩니다.":"백엔드의 최신 분석 결과입니다."}</p></aside></div><div className="bottom-grid"><section id="analysis" className="analysis-card"><Title icon={<Sparkles/>} title="AI 위험 분석 결과" sub="판단 근거와 연쇄 위험"/><h2>{data.analysis.headline}</h2><p>{data.analysis.description}</p><div className="cascade">{data.analysis.flow.map((step,i)=><span key={step} className={i===data.analysis.flow.length-1?"hot":""}>{step}{i<data.analysis.flow.length-1&&<ChevronRight/>}</span>)}</div></section><section className="action-card"><b>+ 지역주민 · 출퇴근 맞춤 행동 추천</b><p>산지 인접 도로 대신 대체 경로를 확인하세요.<br/>저지대·급경사지 주변은 우회해 이동하세요.</p><button className={boundaryAlert?"alert-toggle active":"alert-toggle"} onClick={toggleBoundaryAlert}><BellRing/>{boundaryAlert?"위험 경계 알림 켜짐":"위험 경계 알림 받기"}</button><small>{boundaryAlert?"위험구역 진입 시 화면과 기기 알림으로 알려드려요.":"위치 권한과 알림 권한이 필요합니다."}</small></section></div></section><nav className="mobile-nav"><button className="active" onClick={()=>setView("map")}><ShieldCheck/>위험지도</button><button onClick={()=>document.querySelector(".search-box input")?.scrollIntoView({behavior:"smooth"})}><Search/>지역검색</button><button onClick={()=>setView("profile")}><UserRound/>내 안전</button></nav></>}</main>
}
function Profile({user,history,onSignIn,authLoading,clear,openMap,select}:{user:AuthUser|null;history:string[];onSignIn:()=>void;authLoading:boolean;clear:()=>void;openMap:()=>void;select:(item:string)=>void}){return <section className="profile-page"><div className="profile-heading"><span><UserRound/></span><div><p>내 프로필</p><h1>{user?user.displayName:"Google 로그인이 필요합니다"}</h1><small>{user?user.email:"Google 계정으로 로그인하면 계정 정보와 지역 방문 이력을 확인할 수 있어요."}</small></div></div>{!user&&<button className="profile-login google-profile-login" onClick={onSignIn} disabled={authLoading}><span className="google-mark" aria-hidden="true">G</span><span>{authLoading?"로그인 확인 중…":"Google 계정으로 로그인"}</span></button>}<div className="history-card"><div className="history-title"><History/><div><h2>지역 방문 이력</h2><p>최근 확인한 위험 지역</p></div><button onClick={clear}>전체 삭제</button></div>{history.length?<div className="history-list">{history.map((item,index)=><button key={item} onClick={()=>select(item)}><span><MapPinned/></span><div><b>{item}</b><small>{index===0?"가장 최근 조회":"이전에 조회"}</small></div><ChevronRight/></button>)}</div>:<div className="empty-history"><MapPinned/><p>아직 확인한 지역이 없어요.</p><button onClick={openMap}>위험지도에서 찾아보기</button></div>}</div></section>}
function Risk({icon,tone,title,sub,value}:{icon:React.ReactNode;tone:string;title:string;sub:string;value:string}){return <div><span className={`icon ${tone}`}>{icon}</span><p>{title}<small>{sub}</small></p><b className={riskClass(value)}>{value}</b></div>}
function Title({icon,title,sub}:{icon:React.ReactNode;title:string;sub:string}){return <div className="section-title"><span>{icon}</span><div><p>{title}</p><small>{sub}</small></div></div>}
